server:
  port: 8080
  servlet:
    context-path: /trustestatego

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 400MB
      file-size-threshold: 10MB
      resolve-lazily: false
  datasource:
    url: "jdbc:mysql://localhost:3306/trust_estate_go"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 6
        one-indexed-parameters: true  # page=1 sẽ là trang đầu (mặc định Spring là page=0)
    elasticsearch:
      repositories:
        enabled: true
      client:
        rest:
          uris: http://localhost:9200
#  elasticsearch:
#    uris: http://localhost:9200
#    connection-timeout: 5s
#    socket-timeout: 60s






app:
  api:
    gemini:
      api-key: ${GEMINI_KEY}            # set env var GEMINI_API_KEY
      base-url: https://generativelanguage.googleapis.com
      model: gemini-2.5-flash

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_KEY}
  api-secret: ${CLOUDINARY_SECRET}

jwt:
  signer-key: "0Q6WIzJCAQu7xzibeabCKqV5huSJXjFxsVyxxp5ShhlxP1V88NDUgghB8ZHNwhre"

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.http.converter: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

paypal:
  client:
    id: ${PAYPAL_ID}
    secret: ${PAYPAL_SECRET}
  mode: sandbox
  successUrl: http://localhost:3000/payment-success
  cancelUrl: http://localhost:3000/payment-cancel
  currency: USD