server:
  port: 8080
  servlet:
    context-path: /trustestatego
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      resolve-lazily: true

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/trust_estate_go"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 2        # số record mặc định mỗi trang
        one-indexed-parameters: true  # page=1 sẽ là trang đầu (mặc định Spring là page=0)
  elasticsearch:
    uris: http://localhost:9200
#    username: elastic
#    password: NQbLpkuruBK5c0*80vba

cloudinary:
  cloud-name: diimcwvs5
  api-key: 225587137214427
  api-secret: Y1xcUA7_9U-DB3usTuz2JK1jGME

jwt:
  signer-key: "0Q6WIzJCAQu7xzibeabCKqV5huSJXjFxsVyxxp5ShhlxP1V88NDUgghB8ZHNwhre"