server:
  port: 8080
  servlet:
    context-path: /trustestatego

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 400MB
      file-size-threshold: 10MB
      resolve-lazily: false
  datasource:
#    url: "jdbc:mysql://localhost:3306/trust_estate_go"
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://tramway.proxy.rlwy.net:31429/railway"
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15        # số connection tối đa trong pool
      minimum-idle: 3              # số connection idle tối thiểu
      idle-timeout: 300000         # 5 phút
      max-lifetime: 1800000        # 30 phút, < wait_timeout của MySQL
      connection-timeout: 40000    # 30 giây chờ connection
      validation-timeout: 5000
      leak-detection-threshold: 10000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    web:
      pageable:
        default-page-size: 6
        one-indexed-parameters: true  # page=1 sẽ là trang đầu (mặc định Spring là page=0)
    elasticsearch:
      repositories:
        enabled:  ${app.elastic.enabled}
      client:
#        username:
#        password:
        rest:
#          uris: https://elasticsearch-production-2bfc.up.railway.app
          uris: http://localhost:9200
          connection-timeout: 10s
          socket-timeout: 60s
#          use-ssl: false
#          ssl:
#            verify-hostnames: false

#  elasticsearch:
#    uris: http://localhost:9200
#    connection-timeout: 5s
#    socket-timeout: 60s

app:
  api:
    gemini:
      api-key: ${GEMINI_KEY}            # set env var GEMINI_API_KEY
      base-url: https://generativelanguage.googleapis.com
      model: gemini-2.5-flash

  elastic:
    enabled: true

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_KEY}
  api-secret: ${CLOUDINARY_SECRET}

jwt:
  signer-key: "0Q6WIzJCAQu7xzibeabCKqV5huSJXjFxsVyxxp5ShhlxP1V88NDUgghB8ZHNwhre"

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.http.converter: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    javax.net.ssl: DEBUG


paypal:
  client:
    id: ${PAYPAL_ID}
    secret: ${PAYPAL_SECRET}
  mode: sandbox
  successUrl: https://trustestatego-frontend.onrender.com/payment-success
  cancelUrl: https://trustestatego-frontend.onrender.com/payment-cancel
  currency: USD