server:
  port: 8080
  servlet:
    context-path: /trustestatego

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/trust_estate_go"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cloudinary:
  cloud-name: diimcwvs5
  api-key: 225587137214427
  api-secret: Y1xcUA7_9U-DB3usTuz2JK1jGME